import express from "express";
import { signUp } from "../controllers/auth/signupController.js";
import { Login } from "../controllers/auth/loginController.js";
import verifyToken from "../middleware/verifyToken.js";
import { FindMe } from "../controllers/auth/findMeController.js";
import { Logout } from "../controllers/auth/logoutController.js";
import verifyAdmin from "../middleware/verifyAdmin.js";
import { blockUser } from "../controllers/auth/blockController.js";
import { unblockUser } from "../controllers/auth/unblockController.js";
import { forgotPassword } from "../controllers/auth/forgotPasswordController.js";
import { verifyOtp } from "../controllers/auth/verifyOtpController.js";
import { resetPassword } from "../controllers/auth/resetPasswordController.js";
import { createTournament } from "../controllers/tournaments/createTournamentController.js";
import { getTournamentById } from "../controllers/tournaments/getTournamentByIdController.js";
import { updateTournament } from "../controllers/tournaments/updateTournamentController.js";
import { deleteTournament } from "../controllers/tournaments/deleteTournamentController.js";
import { getOccupiedSlots } from "../controllers/tournaments/occupiedController.js";
import { getBalance, paymentOrderData, transactionData, totalUsers } from "../controllers/authRouterController.js";
import { getTournament } from "../controllers/tournaments/getTournamentController.js";
import { joinTournament } from "../controllers/tournaments/joinTournamentController.js";
import { getMyMatches } from "../controllers/tournaments/myMatchesController.js";
import { getJoinedPlayers } from "../controllers/tournaments/getJoinedPlayers.js";
import { updatePlayerKills } from "../controllers/tournaments/updateKillsController.js";
import { createNotification } from "../controllers/notifications/createNotificationController.js";
import { getNotifications } from "../controllers/notifications/getNotificationController.js";
import { deleteNotification } from "../controllers/notifications/deleteNotificationController.js";
import validateUser from "../middleware/validateUser.js";
import { refreshAccessToken } from "../controllers/auth/refreshTokenController.js";
import { loginLimiter, otpRequestLimiter, otpVerifyLimiter } from "../middleware/rateLimiter.js";

const router = express.Router();

router.post("/signup", validateUser, signUp);
router.post("/login", loginLimiter, Login);
router.post("/logout", Logout);
router.post("/refresh", refreshAccessToken);
router.post("/forgot-password", otpRequestLimiter, forgotPassword);
router.post("/verify-otp", otpVerifyLimiter, verifyOtp);
router.post("/reset-password", resetPassword);
router.get("/me", verifyToken, FindMe);
router.get("/balance", verifyToken, getBalance);
router.get("/order-data", verifyToken, paymentOrderData);
router.get("/transaction", verifyToken, transactionData);
router.get("/tournament/:id", verifyToken, getTournamentById);
router.put("/tournament/:id", verifyToken, verifyAdmin, updateTournament);
router.delete("/tournament/:id", verifyToken, verifyAdmin, deleteTournament);
router.post("/join-tournament/:id", verifyToken, joinTournament);
router.get("/users", verifyToken, totalUsers);
router.patch("/user/:id/block", verifyToken, verifyAdmin, blockUser);
router.patch("/user/:id/unblock", verifyToken, verifyAdmin, unblockUser);
router.post("/tournament/create", verifyToken, verifyAdmin, createTournament);
router.patch("/player/kills", verifyToken, verifyAdmin, updatePlayerKills);
router.get("/tournaments", verifyToken, getTournament);
router.get("/tournament/:id/occupied-slots", verifyToken, getOccupiedSlots);
router.get("/tournament/:id/joined-players", verifyToken, getJoinedPlayers);
router.get("/my-matches", verifyToken, getMyMatches);
router.post("/notification", verifyToken, verifyAdmin, createNotification);
router.get("/get-notifications", verifyToken, getNotifications);
router.delete("/notification/:id", verifyToken, verifyAdmin, deleteNotification);

export default router; 